### ISSUE TITLE
Ran the application.

### ISSUE THREAD

**Issue by Sunny92542** [ivnvxd/hack-interview#8]
I set up the application, but it’s not working. I pressed the A and R buttons, but it’s not generating any output. It’s just saying ‘transcribing audio.’ I tried running YouTube to generate voice and get output using this application.

**Comment by etonealbert** [comment]
problem is that it works with Mac but on windows it returns error PS C:\Users\alber\code\hack-interview> python .\main.py
2024-09-26 17:53:58.920 | DEBUG    | __main__:main:15 - Application started.
2024-09-26 17:55:18.450 | DEBUG    | src.audio:record:35 - Recording...
2024-09-26 17:55:28.857 | DEBUG    | src.gpt_query:transcribe_audio:30 - Transcribing audio from: record.wav...
Exception in thread Thread-3 (_long_func_thread):
Traceback (most recent call last):
  File "C:\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python312\Lib\site-packages\PySimpleGUI\PySimpleGUI.py", line 11813, in _long_func_thread
    return_value = original_func()
                   ^^^^^^^^^^^^^^^
  File "C:\Users\alber\code\hack-interview\src\gpt_query.py", line 32, in transcribe_audio
    with open(path_to_file, "rb") as audio_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'record.wav'
